### ISSUE TITLE
Facebook dev request access

### ISSUE THREAD

**Issue by estathop** [tudoanh/python-facebook-bot#3]
Greetings and kudos for your good work,
My only concern is that during the execution of your code, its requires access to certain features in the facebook API.
My question is which request should I perform to run your code successfully ?
My intuition say it should be the "Page Public Content Access" or "user_tagged_places" or "user_events". Any ideas ?

**Comment by estathop** [comment]
@tudoanh

**Comment by tudoanh** [comment]
You must request the Facebook team to review your app for permission to get Page data.
But it will be hard.

**Comment by tudoanh** [comment]
And since I can not get the required permissions, this repo is not maintain anymore.
